# src/MedicalRag/config/search/search_answer.yaml
milvus:
  client:
    uri: "http://localhost:19530"
    token: "root:Milvus"
    db_name: ""                
    timeout_ms: 30000
    tls: false
    tls_verify: false          
  collection:
    name: "qa_knowledge"  
    description: "RAG QA knowledge base"  
    load_on_start: true

search:
  default_limit: 10
  output_fields: ["question","answer","departments","categories","source_name"]
  pagination:
    page_size: 10
    max_pages: 100
  expr_template: ""                 
  rrf:
    enabled: false   
    k: 100
  channels:
    - name: dense_doc
      field: dense_vec_qa
      enabled: false
      kind: dense_document           
      metric_type: COSINE
      limit: 5
      params: { ef: 256 }
      expr_template: ''   
      weight: 0.1
    - name: sparse_q
      field: sparse_vec_q
      enabled: true
      kind: sparse_query
      metric_type: IP
      limit: 5
      params: { drop_ratio_search: 0.0 }
      expr_template: 'source_name == "{src}"'
      weight: 0.2
    - name: dense_q
      field: dense_vec_q
      enabled: false
      kind: dense_query
      metric_type: COSINE
      limit: 5
      params: { ef: 256 }
      expr_template: ''   
      weight: -1
    - name: sparse_doc
      field: sparse_vec_qa
      enabled: true
      kind: sparse_document
      metric_type: IP
      limit: 5
      params: { drop_ratio_search: 0.0 }
      expr_template: ''   
      weight: 0.8

# 添加embedding配置，这是search需要的
embedding:
  dense:
    provider: ollama                  
    model: "nomic-embed-text"
    base_url: "http://172.16.40.51:11434"
    dim: 768
    normalize: false
    prefixes:
      query: "search_query:"
      document: "search_document:"
  sparse_bm25:
    vocab_path: "vocab.pkl.gz"
    domain_model: "medicine"
    prune_empty_sparse: true
    empty_sparse_fallback: { "0": 0.0 }
    stopwords: ["什么","？","是","如何"]
    k1: 1.5
    b: 0.75