milvus:
  uri: http://localhost:19530
  token: null
  collection_name: medical_knowledge
  drop_old: true
  auto_id: false

embedding:
  summary_dense:
    provider: ollama
    model: bge-m3:latest
    base_url: http://localhost:11434
    dimension: 1024
  text_dense:
    provider: ollama
    model: bge-m3:latest
    base_url: http://localhost:11434
    dimension: 1024
  text_sparse:
    provider: self
    vocab_path_or_name: vocab.pkl.gz
    algorithm: BM25
    domain_model: medicine
    k1: 1.5
    b: 0.75
    build:
      workers: 8
      chunksize: 64

llm:
  provider: ollama
  model: qwen3:32b
  base_url: http://localhost:11434
  temperature: 0.1

data:
  summary_field: question
  document_field: answer
  default_source: qa
  default_source_name: huatuo_qa
  default_lt_doc_id: ''
  default_chunk_id: -1

multi_dialogue_rag: 
  estimate_token_fun: tiktoken
  llm_max_token: 1024
  cut_dialogue_scale: 2   # 裁切一次砍一半
  max_token_threshold: 1.01
  smith_debug: false
  console_debug: true
  thinking_in_context: false
