# 数据入库配置
# 数据处理
batch_size: 100
max_workers: 4
chunk_size: null  # 文本分块大小，null表示不分块
chunk_overlap: null  # 文本分块重叠

# 重试机制
max_retries: 3
retry_delay: 1.0

# 向量化选项
build_vocab_if_needed: true
update_existing: false  # 是否更新已存在的文档

# 预处理
clean_text: true
remove_duplicates: true
min_text_length: 10
max_text_length: 10000

# 进度保存
save_progress: true
progress_file: "ingestion_progress.json"