ingest:
  source_name_default: "huatuo_qa"
  input_path: "raw_data/tf-data/qa.temp_10.json"
  fields_mapping:
    id: "id"
    question: "question"
    answer: "answer"
    departments: "departments"
    categories: "categories"
    reasoning: "reasoning"