app:
  env: dev
  log_level: INFO

milvus:
  client:
    uri: "http://localhost:19530"
    token: "root:Milvus"
    db_name: ""                # 为空用默认
    timeout_ms: 30000
    tls: false
    tls_verify: false          # 自签名可关
  collection:
    name: "qa_knowledge"  # collection名字
    description: "RAG QA knowledge base"  # collection描述
    recreate_if_exists: false  # 开发期可设 true，生产要小心
    num_partitions: 128
    load_on_start: true
    properties:
      partitionkey.isolation: true     # 仅 HNSW 生效
  schema:
    auto_id: false
    enable_dynamic_field: true
    fields:
      - name: id
        dtype: VARCHAR
        max_length: 64
        is_primary: true
      - name: dept_pk
        dtype: VARCHAR
        max_length: 32
        is_partition_key: true
      - name: question
        dtype: VARCHAR
        max_length: 65535
        enable_analyzer: true
      - name: answer
        dtype: VARCHAR
        max_length: 65535
        enable_analyzer: true
      - name: qa_text
        dtype: VARCHAR
        max_length: 65535
        enable_analyzer: true
      - name: dense_vec_q
        dtype: FLOAT_VECTOR
        dim: 768
      - name: dense_vec_qa
        dtype: FLOAT_VECTOR
        dim: 768
      - name: sparse_vec_q
        dtype: SPARSE_FLOAT_VECTOR
      - name: sparse_vec_qa
        dtype: SPARSE_FLOAT_VECTOR
      - name: departments
        dtype: ARRAY
        element_type: INT64
        max_length: 32
        max_capacity: 6
      - name: categories
        dtype: ARRAY
        element_type: INT64
        max_length: 32
        max_capacity: 8
      - name: source_name
        dtype: VARCHAR
        max_length: 65535
  index:
    build_on_create: true
    by_field:
      dense_vec_qa:
        index_type: HNSW
        metric_type: COSINE           # 与嵌入相匹配（COSINE/IP）
        params: { M: 32, efConstruction: 200 }
      dense_vec_q:
        index_type: HNSW
        metric_type: COSINE
        params: { M: 32, efConstruction: 200 }
      sparse_vec_qa:
        index_type: SPARSE_INVERTED_INDEX
        metric_type: IP               # 手动 BM25 用 IP；内置 BM25 用 BM25
        params: { inverted_index_algo: DAAT_MAXSCORE }
      sparse_vec_q:
        index_type: SPARSE_INVERTED_INDEX
        metric_type: IP
        params: { inverted_index_algo: DAAT_MAXSCORE }

  search:
    default_limit: 10
    output_fields: ["question","answer","departments","categories","source_name"]
    pagination:
      page_size: 10
      max_pages: 100
    expr_template: ""                 # 例如: 'dept_pk in ["1","2"] and id != "{exclude_id}"'
    rrf:
      enabled: false   # false 则使用 WeightedRanker
      k: 100
    # 各检索通道（可开关、可配参数）
    channels:
      - name: dense_doc
        field: dense_vec_qa
        enabled: false
        kind: dense_document           # dense_document | dense_query | sparse_document | sparse_query
        metric_type: COSINE
        limit: 5
        params: { ef: 256 }
        expr_template: ''   # 可为空，使用顶层的；也可写成 'id != "{exclude_id}"'
        weight: 0.1
      - name: sparse_q
        field: sparse_vec_q
        enabled: true
        kind: sparse_query
        metric_type: IP
        limit: 5
        params: { drop_ratio_search: 0.0 }
        expr_template: 'source_name == "{src}"'
        weight: 0.2
      - name: dense_q
        field: dense_vec_q
        enabled: false
        kind: dense_query
        metric_type: COSINE
        limit: 5
        params: { ef: 256 }
        expr_template: ''   # 可为空，使用顶层的；也可写成 'id != "{exclude_id}"'
        weight: -1
      - name: sparse_doc
        field: sparse_vec_qa
        enabled: true
        kind: sparse_document
        metric_type: IP
        limit: 5
        params: { drop_ratio_search: 0.0 }
        expr_template: ''   # 可为空，使用顶层的；也可写成 'id != "{exclude_id}"'
        weight: 0.8

  write:
    consistency_level: Bounded        # Strong/Bounded/Eventually
    batch_size: 512
    id_field: "id"
    partition_key_field: "dept_pk"
    upsert: true
    auto_load_after_write: true
    flush_interval_ms: 0              # 0 表示立即
    compaction:
      enabled: true
      interval_sec: 300
      sealed_segments_only: true
      threshold_deleted_ratio: 0.5

  delete:
    allow_hard_delete: true
    soft_delete_field: ""             # 若非空，则打标软删

embedding:
  dense:
    provider: ollama                  # ollama | openai | hf
    model: "nomic-embed-text"
    base_url: "http://172.16.40.51:11434"
    dim: 768
    normalize: false
    prefixes:
      query: "search_query:"
      document: "search_document:"
  sparse_bm25:
    vocab_path: "vocab.pkl.gz"
    domain_model: "medicine"
    prune_empty_sparse: true
    empty_sparse_fallback: { "0": 0.0 } # 字典 key 会被转 int
    stopwords: ["什么","？","是","如何"]
    k1: 1.5
    b: 0.75

ingest:
  source_name_default: "huatuo_qa"
  input_path: "raw_data/tf-data/qa.temp_10.json"
  fields_mapping:
    id: "id"
    question: "question"
    answer: "answer"
    departments: "departments"
    categories: "categories"
    reasoning: "reasoning"

