annotation: 
  raw_data: 
    path: "data/raw/qa/train_datasets.jsonl"
    format: "jsonl"  # 支持原始json，jsonl
  service:
    ollama:  # ollama的url非空则优先使用ollama，否则openai
      url: "http://localhost:11434"
      key: "ollama"
      model: "qwen3:32b"
      max_retries: 10
    openai: 
      url: "https://api.openai.com/v1/responses"
      key: ""
      model: "gpt-4o-mini-2024-07-18"
      proxy: "http://127.0.0.1:10809"
model:
  embedding:
    path: "model/xxx"  # 只支持从huggingface中下载下来的本地目录进行加载模型
    device: "cuda:0"
  llm:
    path: ""  # path为空则代表使用服务调用的形式使用llm
    device: "cuda:0"
    service:
      ollama: 
        url: "http://localhost:11434"
        key: ""
        model: "qwen3:32b"
        max_retries: 10
      openai: 
        url: "https://api.openai.com/v1/responses"
        key: ""
        model: "gpt-4o-mini-2024-07-18"
        proxy: "http://127.0.0.1:10809"